# -*- coding: utf-8 -*-
"""MLops_Feast_SkillGap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHkEMnM3N_7yjk3PP1-KPsTCZi4eYVOP
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

file_name = "CSE_Curriculum_Industry_Skill_Alignment_4_Datasets_500_Each.xlsx"

excel_file = pd.ExcelFile(file_name)

print(excel_file.sheet_names)

graduate_skills = pd.read_excel(
    file_name,
    sheet_name="Graduate_Skills"
)

curriculum_industry = pd.read_excel(
    file_name,
    sheet_name="Curriculum_Industry"
)

decision_framework = pd.read_excel(
    file_name,
    sheet_name="Decision_Framework"
)

training_outcomes = pd.read_excel(
    file_name,
    sheet_name="Training_Outcomes"
)

print("Graduate Skills:", graduate_skills.shape)
print("Curriculum Industry:", curriculum_industry.shape)
print("Decision Framework:", decision_framework.shape)
print("Training Outcomes:", training_outcomes.shape)

print("Graduate Skills Columns:")
print(graduate_skills.columns.tolist())

print("Curriculum Industry Columns:")
print(curriculum_industry.columns.tolist())

print("Decision Framework Columns:")
print(decision_framework.columns.tolist())

print("Training Outcomes Columns:")
print(training_outcomes.columns.tolist())

graduate_skills.head()

graduate_skills.info()

graduate_skills.describe(include="all")

print("Graduate Skills Missing Values")
print(graduate_skills.isnull().sum())

print("\nCurriculum Industry Missing Values")
print(curriculum_industry.isnull().sum())

print("\nDecision Framework Missing Values")
print(decision_framework.isnull().sum())

print("\nTraining Outcomes Missing Values")
print(training_outcomes.isnull().sum())

print("Graduate Skills duplicates:",
      graduate_skills.duplicated().sum())

print("Curriculum Industry duplicates:",
      curriculum_industry.duplicated().sum())

print("Decision Framework duplicates:",
      decision_framework.duplicated().sum())

print("Training Outcomes duplicates:",
      training_outcomes.duplicated().sum())

from google.colab import drive
drive.mount('/content/drive')